# Generated by Django 4.2.1 on 2023-05-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_ram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videocard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('firm', models.CharField()),
                ('memory_size', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
        ),
        migrations.AddField(
            model_name='ram',
            name='memory_size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
