# Generated by Django 4.2.1 on 2023-05-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0010_alter_coolingsystem_price_alter_hdd_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SDD',
            new_name='SSD',
        ),
        migrations.AlterField(
            model_name='videocard',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
